### PR TITLE
feat(output): adds the output option

### PR DESCRIPTION
**Pull request by maasencioh**

### CODE REVIEW

**Comment by targos** [comment]
for the commit message:
* you are allowed to omit the parentheses. `doc: update history ...` is valid
* no need to put the name of the library `feat: add output ...` is enough
* if it fixes or closes a bug, it should be on its own line. example:
```
feat: blabla

Fixes #5
Closes #9
```

**Comment by targos** [comment]
reminder to amend the messages: `git rebase -i master`

**Comment by maasencioh** [comment]
updated

**Comment by targos** [comment]
thank you

**Comment by targos** [comment]
you added the matrix implementation in the changelog but it is not implemented yet, right ?

**Comment by maasencioh** [comment]
It's not yet implemented, it's kind of my TODO list of versions

**Comment by targos** [comment]
well it will be in 1.1 or more ;)

**Comment by maasencioh** [comment]
Yes I saw it

**Pull request merged**
